name:CI pipeline
on:
push:
branches:
-main
-fearure/*
pull_request:
branches:
-main

jobs:
build:
runs-on:ubuntu-latest

step:
-name:Checkout code
uses: actions/checkout@v3

-name:set up .NET
uses:action/setup-dotnet@v3
with:
dotnet-version:'6.x'

-name: Restore Dependencies
run:dotnet restore

-name:Build Applicaton
run:dotnet build -- configuration Release

-name:Run Test
run:dotnet test-- configuration Release--logger trx

-name: Publish Test Results
uses:action/upload-artifact@v3
with
name:test-results
path:'**/*.trx'
